server:
  port: 8080

#配置mybatis属性
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.sdx.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#配置spring基本属性
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course_test1
    username: root
    password: sdx11233.0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#配置阿里云oss存储服务
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    region: cn-hangzhou
    accessKeyId: LTAI5tAULtLChU7PwJyMFg1U
    accessKeySecret: IBLiV7XdaD6AgOxAnvveAQtOzEp7xg
    roleArn: acs:ram::1803191474721426:role/myroler
    bucketName: hdcat


#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug